[workspace]
members = [
    "contracts/collateral_token",
    "contracts/debt_token",
    "contracts/lending_pool",
    "contracts/flash_liquidator",
    "contracts/lending_pool_v2",
    "contracts/flash_loan_pool",
]
resolver = "2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
